install.packages("devtools")
install.packages("ggplot2")
install.packages("stats")
install.packages("circular", dependencies = TRUE)
install.packages("circular", repos="https://cran.r-project.org/web/packages/circular/index.html",type="source")
install.packages("dplyr")
install.packages("r-cran-circular")
